@host = http://localhost:5000
@contentType = application/json
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzUxNTQxODQ1fQ.xJWEJpe-W5M2-oYx1gPvvQIjgXpmhUBEJpVlb43996U
@userToken = 

@refreshToken = 

### 1. Аутентификация и пользователи ###

### Регистрация нового пользователя
POST {{host}}/api/users/register
Content-Type: {{contentType}}

{
  "email": "user@mail.com",
  "password": "Password",
  "firstName": "Иван",
  "middleName": "Иванович",
  "lastName": "Иванов"
}

### Авторизация пользователя
POST {{host}}/api/users/login
Content-Type: {{contentType}}

{
  "email": "Admin",
  "password": "Password"
}

### Получить всех пользователей (требует авторизации)
GET {{host}}/api/users
Authorization: Bearer {{adminToken}}

### Получить пользователя по ID
GET {{host}}/api/users/1
Authorization: Bearer {{adminToken}}

### Обновить данные пользователя
PUT {{host}}/api/users/1
Content-Type: {{contentType}}
Authorization: Bearer {{userToken}}

{
  "email": "updated@mail.com",
  "firstName": "НовоеИмя",
  "middleName": "НовоеОтчество",
  "lastName": "НоваяФамилия",
  "phoneNumber": "+79991234567"
}

### Сменить пароль
PUT {{host}}/api/users/1/changepassword
Content-Type: {{contentType}}
Authorization: Bearer {{userToken}}

{
  "oldPassword": "Password123!",
  "newPassword": "NewPassword123!"
}

### Удалить пользователя
DELETE {{host}}/api/users/1
Authorization: Bearer {{adminToken}}

### Обновить токены
POST {{host}}/api/users/generatetokens
Content-Type: {{contentType}}

{
  "token": "your_refresh_token_here"
}

### 2. Роли ###

### Создать новую роль
POST {{host}}/api/roles
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Admin"
}

### Получить все роли
GET {{host}}/api/roles
Authorization: Bearer {{adminToken}}

### Получить роль по ID
GET {{host}}/api/roles/1
Authorization: Bearer {{adminToken}}

### Обновить роль
PUT {{host}}/api/roles/1
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "UpdatedRoleName"
}

### Удалить роль
DELETE {{host}}/api/roles/1
Authorization: Bearer {{adminToken}}

### 3. Назначение ролей пользователям ###

### Назначить роль пользователю
POST {{host}}/api/userroles
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "userId": 6,
  "roleId": 1
}

### Получить все назначения ролей
GET {{host}}/api/userroles
Authorization: Bearer {{adminToken}}

### Получить назначение по ID
GET {{host}}/api/userroles/1
Authorization: Bearer {{adminToken}}

### Обновить роль пользователя
PUT {{host}}/api/userroles/1
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "roleId": 3
}

### Удалить назначение роли
DELETE {{host}}/api/userroles/1
Authorization: Bearer {{adminToken}}

### 4. Категории (полный шаблон) ###

### 1. Создание родительских категорий ###

### Родительская категория 1: Одежда
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Одежда",
  "description": "Мужская, женская и детская одежда"
}

### Родительская категория 2: Посуда
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Посуда",
  "description": "Кухонная и столовая посуда"
}

### Родительская категория 3: Интерьер
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Интерьер",
  "description": "Предметы для оформления интерьера"
}

### Родительская категория 4: Текстиль
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Текстиль",
  "description": "Тканевые изделия для дома"
}

### Родительская категория 5: Аксессуары
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Аксессуары",
  "description": "Дополнительные элементы гардероба и интерьера"
}


### 2. Создание дочерних категорий ###

### Дочерние для Одежды (ID родителя: 1)
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Женская одежда",
  "description": "Одежда для женщин",
  "parentCategoryId": 1
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Мужская одежда",
  "description": "Одежда для мужчин",
  "parentCategoryId": 1
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Детская одежда",
  "description": "Одежда для детей",
  "parentCategoryId": 1
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Спортивная одежда",
  "description": "Одежда для занятий спортом",
  "parentCategoryId": 1
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Домашняя одежда",
  "description": "Одежда для дома",
  "parentCategoryId": 1
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Верхняя одежда",
  "description": "Пальто, куртки, пуховики",
  "parentCategoryId": 1
}


### Дочерние для Посуда (ID родителя: 2)
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Кухонная посуда",
  "description": "Кастрюли, сковороды, ковши",
  "parentCategoryId": 2
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Столовая посуда",
  "description": "Тарелки, блюда, салатницы",
  "parentCategoryId": 2
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Стеклянная посуда",
  "description": "Стаканы, бокалы, фужеры",
  "parentCategoryId": 2
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Посуда для сервировки",
  "description": "Сервировочные наборы, подносы",
  "parentCategoryId": 2
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Посуда для приготовления",
  "description": "Формы для выпечки, ножи",
  "parentCategoryId": 2
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Посуда для хранения",
  "description": "Контейнеры, банки для сыпучих",
  "parentCategoryId": 2
}


### Дочерние для Интерьер (ID родителя: 3)
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Мебель",
  "description": "Предметы мебели для дома",
  "parentCategoryId": 3
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Декор",
  "description": "Декоративные элементы",
  "parentCategoryId": 3
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Освещение",
  "description": "Лампы, светильники, бра",
  "parentCategoryId": 3
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Зеркала",
  "description": "Настенные и напольные зеркала",
  "parentCategoryId": 3
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Картины и постеры",
  "description": "Художественные произведения",
  "parentCategoryId": 3
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Часы",
  "description": "Настенные и настольные часы",
  "parentCategoryId": 3
}


### Дочерние для Текстиль (ID родителя: 4)
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Постельное белье",
  "description": "Комплекты постельного белья",
  "parentCategoryId": 4
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Пледы и покрывала",
  "description": "Текстиль для спальни",
  "parentCategoryId": 4
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Шторы",
  "description": "Гардины, портьеры, занавески",
  "parentCategoryId": 4
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Полотенца",
  "description": "Банные и кухонные полотенца",
  "parentCategoryId": 4
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Ковры",
  "description": "Ковровые покрытия",
  "parentCategoryId": 4
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Скатерти",
  "description": "Скатерти и салфетки",
  "parentCategoryId": 4
}


### Дочерние для Аксессуары (ID родителя: 5)
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Сумки",
  "description": "Женские и мужские сумки",
  "parentCategoryId": 5
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Ремни",
  "description": "Кожаные и текстильные ремни",
  "parentCategoryId": 5
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Головные уборы",
  "description": "Шляпы, кепки, шапки",
  "parentCategoryId": 5
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Шарфы и платки",
  "description": "Шейные аксессуары",
  "parentCategoryId": 5
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Бижутерия",
  "description": "Украшения и аксессуары",
  "parentCategoryId": 5
}
###
POST {{host}}/api/categories
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Зонты",
  "description": "Зонты и дождевики",
  "parentCategoryId": 5
}